texts:
  1:
    - '&c╔'
    - '&c║ &fИгрок &c%player% &fкупил %donate%&f!'
    - '&c║ &fНа сайте: &cwww.ShineGrief.com'
    - '&c║ &fСпасибо за поддержку сервера!'
    - '&c╚'
  2:
    - '&c╔'
    - '&c║ &fИгрок &c%player% &fкупил %donate%&f!'
    - '&c║ &fНа сайте: &cwww.ShineGrief.com'
    - '&c║ &fВладелец желает ему счастья!'
    - '&c╚'
  3:
    - '&c╔'
    - '&c║ &fИгрок &c%player% &fкупил %donate%&f!'
    - '&c║ &fНа сайте: &cwww.ShineGrief.com'
    - '&c║ &fПоздравляем его с данной покупкой!'
    - '&c╚'
messages:
  no-perms: '&c&lДОНАТ &8◦ &fУ Вас нет прав.'
  usage:
    - '&c&lДОНАТ &8◦ &fПомощь:'
    - '&c/fmam reload &f- перезагрузить плагин.'
    - '&c/fmad send &f(&cНикнейм&f) (&cТекст&f) - написать сообщение о покупке доната.'
  title: '&c&lДОНАТ'
  subtitle: '&c%player% &fкупил %donate%&f!'
  success-send: '&c&lДОНАТ &8◦ &fВы &aуспешно &fотправили сообщение о покупке доната!'
  success-reload: '&c&lДОНАТ &8◦ &fВы перезагрузили плагин!'